mainconv/urls.py
from django.conf.urls import url
from . import views

app_name = 'mainconv'
urlpatterns = [
	url(r'^$', views.home, name='home'),
	url(r'^rst2html/$', views.rst2html, name='rst2html'),
	url(r'^filelist/$', views.filelist, name='filelist'),
	url(r'^editor/$', views.editor, name='editor'),
	url(r'^text2html/$', views.text2html, name='text2html'),
	url(r'^text2preview/$', views.text2preview, name='text2preview'),
	url(r'^show/(?P<filename>[a-z,A-Z,0-9]+)', views.show, name='show'),
	url(r'^showedit/(?P<filename>[a-z,A-Z,0-9]+)', views.showedit, name='showedit'),
	url(r'^delete/(?P<filename>[a-z,A-Z,0-9]+)', views.delete, name='delete'),
	url(r'^upload/$', views.upload_img_page, name='upload_img_page'),
	url(r'^uploadimg/$', views.upload_img, name='upload_img')
]

rst2html/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('mainconv.urls')),
    url(r'^admin/', admin.site.urls),
]

mainconv/models.py
from django.db import models

# Create your models here.

mainconv/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.core.files import File
from django.core.files.storage import default_storage
import os, time

def home(request):
	return render(request,'home.html')

def rst2html(request):
	path = 'mainconv/uploadTemp/'
	name = request.POST['name']
	style = request.POST['style']
	file = request.FILES['uploadedFile']
	savePath = default_storage.save(path,file)
	os.rename(savePath,'{}upload.rst'.format(path))
	source = 'mainconv/uploadTemp/upload.rst'
	destination = 'mainconv/templates/outputTemp/' + name + '.html'
	if style == 'basic':
		os.system('rst2html5 ' + source + ' > ' + destination)
	elif style == 'deck':
		os.system('rst2html5 --deck-js --pretty-print-code --embed-content ' + source + ' > ' + destination)
	elif style == 'reveal':
		os.system('rst2html5 --jquery --reveal-js --pretty-print-code ' + source + ' > ' + destination)
	elif style == 'bootstrap':
		os.system('rst2html5 --bootstrap-css --pretty-print-code --jquery --embed-content ' + source + ' > ' + destination)
	return render(request,'outputTemp/'+name+'.html')

def filelist(request):
	filepath = 'mainconv/templates/outputTemp/'
	fl = []
	for file in os.listdir(filepath):
		filename,extention = os.path.splitext(file)
		if extention == '.html':
			fl.append(filename)
		fl.sort()
		context = {'filelist':fl}
	return render(request,'list.html',context)

def show(request,filename):
	return render(request,'outputTemp/'+filename+'.html')

def showedit(request,filename):
	return render(request,'previewTemp/'+filename+'.html')

def delete(request,filename):
	filepath = 'mainconv/templates/outputTemp/' + filename + '.html'
	os.remove(filepath)
	return HttpResponseRedirect(reverse('mainconv:filelist'))

def editor(request):
	return render(request,'editor.html')

def text2html(request):
	path = 'mainconv/uploadTemp/'
	name = request.POST['name']
	style = request.POST['style']
	f = open(path+'upload.rst', 'w')
	f.write(request.POST['text'])
	f.close()
	source = 'mainconv/uploadTemp/upload.rst'
	destination = 'mainconv/templates/outputTemp/' + name + '.html'
	if style == 'basic':
		os.system('rst2html5 ' + source + ' > ' + destination)
	elif style == 'deck':
		os.system('rst2html5 --deck-js --pretty-print-code --embed-content ' + source + ' > ' + destination)
	elif style == 'reveal':
		os.system('rst2html5 --jquery --reveal-js --pretty-print-code ' + source + ' > ' + destination)
	elif style == 'bootstrap':
		os.system('rst2html5 --bootstrap-css --pretty-print-code --jquery --embed-content ' + source + ' > ' + destination)
	return render(request,'outputTemp/'+name+'.html')

def text2preview(request):
	path = 'mainconv/uploadTemp/'
	name = request.POST['name']
	style = request.POST['style']
	f = open(path+'upload.rst', 'w')
	f.write(request.POST['text'])
	f.close()
	source = 'mainconv/uploadTemp/upload.rst'
	destination = 'mainconv/templates/previewTemp/' + name + '.html'
	if style == 'basic':
		os.system('rst2html5 ' + source + ' > ' + destination)
	elif style == 'deck':
		os.system('rst2html5 --deck-js --pretty-print-code --embed-content ' + source + ' > ' + destination)
	elif style == 'reveal':
		os.system('rst2html5 --jquery --reveal-js --pretty-print-code ' + source + ' > ' + destination)
	elif style == 'bootstrap':
		os.system('rst2html5 --bootstrap-css --pretty-print-code --jquery --embed-content ' + source + ' > ' + destination)
	return render(request,'previewTemp/'+name+'.html')

def upload_img_page(request):
	return render(request,'upload.html')

def upload_img(request):
	path = 'mainconv/static/images/'
	name = request.POST['name']
	file = request.FILES['uploadedFile']
	savePath = default_storage.save(path,file)
	os.rename(savePath,path+name)
	img = '/static/images/' + name
	context = {'img':img}
	return render(request,'preview.html',context)

mainconv/templates/editor.html
<html>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
<head>
<title>rst2html - Editor</title>
<script src="{% static 'angular.min.js' %}"></script>
<script>
var app = angular.module('myApp', []);
app.controller('personCtrl', function($scope) {
	$scope.myVar = false;
	$scope.toggle_preview = function() {
		$scope.preview = !$scope.preview;
    };
	$scope.toggle_insert_pic = function() {
		$scope.insert_pic = !$scope.insert_pic;
    };
});
</script>
<script>
function font_bold(){
	if(document.getElementById('text').style.fontWeight == 'bold'){
		document.getElementById('text').style.fontWeight = 'normal';
		document.getElementById('bold_button').style.fontWeight = 'normal';
	}else{
		document.getElementById('text').style.fontWeight = 'bold';
		document.getElementById('bold_button').style.fontWeight = 'bold';
	}	
}
function font_italic(){
	if(document.getElementById('text').style.fontStyle == 'italic'){
		document.getElementById('text').style.fontStyle = 'normal';
		document.getElementById('italic_button').style.fontStyle = 'normal';
	}else{
		document.getElementById('text').style.fontStyle = 'italic';
		document.getElementById('italic_button').style.fontStyle = 'italic';
	}	
}
function addimg() {
	temp = document.getElementById("text").value
	img_url = document.getElementById("url").value
	if(img_url != ''){
		document.getElementById("text").value = temp + '.. image:: ' + img_url + '\n';
	}
}
</script>
</head>
<body>
<div class="main" ng-app="myApp" ng-controller="personCtrl">
<h3>
<form action="{% url 'mainconv:filelist' %}" method="post">
{% csrf_token %}
	<input type="submit" value="rst2html" formaction="{% url 'mainconv:home' %}" class="logo">
	<input type="submit" value="home" formaction="{% url 'mainconv:home' %}" class="link">
	<input type="submit" value="editor" formaction="{% url 'mainconv:editor' %}" class="link">
	<input type="submit" value="filelist" class="link">
</form>
</h3>
<form action="{% url 'mainconv:text2html' %}" method="post" enctype="multipart/form-data">
{% csrf_token %}
	Output name : <input type="text" name="name" pattern="[A-Za-z]+" required>
	Style : <select name="style">
		<option value="basic">basic</option>
		<option value="deck">deck</option>
		<option value="bootstrap">bootstrap</option>
	</select>
	<div class="style">
	Editor font style : 
		<select>
			<option onclick="document.getElementById('text').style.fontSize = '10px'">10px</option>
			<option onclick="document.getElementById('text').style.fontSize = '12px'">12px</option>
			<option onclick="document.getElementById('text').style.fontSize = '14px'">14px</option>
			<option onclick="document.getElementById('text').style.fontSize = '16px'">16px</option>
			<option onclick="document.getElementById('text').style.fontSize = '18px'">18px</option>
			<option onclick="document.getElementById('text').style.fontSize = '20px'">20px</option>
		</select>
		<button type="button" onclick="font_italic()" class="small" id="italic_button">I</button>
		<button type="button" onclick="font_bold()" class="small" id="bold_button">B</button>
		<button type="button" onclick="document.getElementById('text').style.color = 'black'" class="small" id="black">B</button>
		<button type="button" onclick="document.getElementById('text').style.color = 'red'" class="small" id="red">R</button>
		<button type="button" onclick="document.getElementById('text').style.color = 'green'" class="small" id="green">G</button>
		<button type="button" onclick="document.getElementById('text').style.color = 'blue'" class="small" id="blue">B</button>
		<button type="button" ng-click="toggle_insert_pic()">insert image</button>
			<p ng-show="insert_pic">
			image url : <input type="text" id="url" size="50" placeholder="Insert your image url here...">
						<button type="button" onclick="addimg()">insert</button>
						<button formaction="{% url 'mainconv:upload_img_page' %}" formtarget="_blank">upload</button>
			</p>
	</div>
	<textarea id="text" name="text" placeholder="Edit your RST here..." id="field" required></textarea></br>
	<button ng-click="toggle_preview()" formaction="{% url 'mainconv:text2preview' %}" formtarget="preview_iframe">Preview</button>
		<p ng-show="preview"><button formaction="{% url 'mainconv:text2preview' %}" formtarget="preview_iframe">Refresh</button></br>
		<iframe src="" width="100%" height="500px" id="preview_iframe" name="preview_iframe"></iframe></p>
	<input type="submit" value="Submit">
</form>
</div>
</body>
</html>

mainconv/templates/home.html
<html>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
<head>
<title>rst2html - Home</title>
</head>
<body>
<div class="main">
<h3>
<form action="{% url 'mainconv:filelist' %}" method="post">
{% csrf_token %}
	<input type="submit" value="rst2html" formaction="{% url 'mainconv:home' %}" class="logo">
	<input type="submit" value="home" formaction="{% url 'mainconv:home' %}" class="link">
	<input type="submit" value="editor" formaction="{% url 'mainconv:editor' %}" class="link">
	<input type="submit" value="filelist" class="link">
</form>
</h3>
<form action="{% url 'mainconv:rst2html' %}" method="post" enctype="multipart/form-data">
{% csrf_token %}
	Input RST file : <input type="file" name="uploadedFile" accept=".rst" required></br>
	Output name : <input type="text" name="name" pattern="[A-Za-z]+" required>
	Style : <select name="style"  id="select_box">
		<option value="basic">basic</option>
		<option value="deck">deck</option>
		<option value="bootstrap">bootstrap</option>
	</select></br>
	<input type="submit" value="Submit">
</form>
</div>
</body>
</html>

mainconv/templates/list.html
<html>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
<head>
<title>rst2html - File list</title>
<script src="{% static 'angular.min.js' %}"></script>
<script>
var app = angular.module("myApp", []);
app.controller("myCtrl", function($scope) {
	{% if filelist %}
	$scope.filelist = [
	{% for file in filelist %}{"name":"{{ file }}"},
	{% endfor %}]
	{% endif %}
});
</script>
</head>
<body ng-app="myApp" ng-controller="myCtrl">
<div class="main">
<h3>
<form action="{% url 'mainconv:filelist' %}" method="post">
{% csrf_token %}
	<input type="submit" value="rst2html" formaction="{% url 'mainconv:home' %}" class="logo">
	<input type="submit" value="home" formaction="{% url 'mainconv:home' %}" class="link">
	<input type="submit" value="editor" formaction="{% url 'mainconv:editor' %}" class="link">
	<input type="submit" value="filelist" class="link">
</form>
</h3>
	{% if filelist %}
	Search: <input type="text" ng-model="search">
	<table width=100% border="1" id="table">
		<tr ng-repeat="file in filelist | filter:search">
			<td><a href="/show/{%verbatim%}{{ file.name }}{%endverbatim%}"><span ng-bind="file.name"></span></a></td>
			<td width=20% align="right"><a href="/delete/{%verbatim%}{{ file.name }}{%endverbatim%}" class="hvr-buzz">delete</a></td>
		</tr>
	</table>
	{% else %}
		<p>No file available.</p>
	{% endif %}
</br>
</div>
</body>
</html>

mainconv/templates/outputTemp/testbasic.html
<!DOCTYPE html><html><head><meta charset="utf-8"><title></title><style type="text/css">body{
 font-family: helvetica;
 color: #222;
}

li>p{
 margin-bottom: 0;
}

.line{
 margin-bottom: 0.3em;
 display: table;
}

.admonition-title {
    font-size: 1.3em;
    font-weight: bold;
}

aside{
 float: right;
 width: 20%;
 display: table;
 padding: 1em;
 margin: 1em;
 margin-right: 0;
}

.footnote, .cite{
 width: 98%;
 display: table;
 border: 1px solid #ddd;
 padding: 0.5%;
 margin: 0.5%;
}

.footnote .du-label, .cite .du-label{
 float: left;
 height: 100%;
 width: 5%;
 margin-right: 1em;
 padding: 0.5%;
 text-align: center;
 display: table;
}

th, th p{
 font-weight: bold;
}

.field-label{
 font-weight: bold;
}

ol.arabic{
 list-style-type: decimal;
}

ol.loweralpha{
 list-style-type: lower-alpha;
}

ol.upperalpha{
 list-style-type: upper-alpha;
}

ol.lowerroman{
 list-style-type: lower-roman;
}

ol.upperroman{
 list-style-type: upper-roman;
}

img.align-left{
 float: left;
}

img.align-right{
 float: right;
}
</style></head><body><img alt="/static/images/54578303_p0.jpg" src="/static/images/54578303_p0.jpg"></body></html>

mainconv/templates/outputTemp/testname.html
<!DOCTYPE html><html><head><meta charset="utf-8"><title></title><style type="text/css">body{
 font-family: helvetica;
 color: #222;
}

li>p{
 margin-bottom: 0;
}

.line{
 margin-bottom: 0.3em;
 display: table;
}

.admonition-title {
    font-size: 1.3em;
    font-weight: bold;
}

aside{
 float: right;
 width: 20%;
 display: table;
 padding: 1em;
 margin: 1em;
 margin-right: 0;
}

.footnote, .cite{
 width: 98%;
 display: table;
 border: 1px solid #ddd;
 padding: 0.5%;
 margin: 0.5%;
}

.footnote .du-label, .cite .du-label{
 float: left;
 height: 100%;
 width: 5%;
 margin-right: 1em;
 padding: 0.5%;
 text-align: center;
 display: table;
}

th, th p{
 font-weight: bold;
}

.field-label{
 font-weight: bold;
}

ol.arabic{
 list-style-type: decimal;
}

ol.loweralpha{
 list-style-type: lower-alpha;
}

ol.upperalpha{
 list-style-type: upper-alpha;
}

ol.lowerroman{
 list-style-type: lower-roman;
}

ol.upperroman{
 list-style-type: upper-roman;
}

img.align-left{
 float: left;
}

img.align-right{
 float: right;
}
</style></head><body><p>asdasd</p></body></html>

mainconv/templates/preview.html
<html>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
<head>
<title>rst2html - Image preview</title>
</head>
<body>
<div class="main">
<img src="{{img}}"></br>
<b>url : <i>{{img}}</i></b>
</div>
</body>
</html>

mainconv/templates/previewTemp/testbasic.html
<!DOCTYPE html><html><head><meta charset="utf-8"><title></title><style type="text/css">body{
 font-family: helvetica;
 color: #222;
}

li>p{
 margin-bottom: 0;
}

.line{
 margin-bottom: 0.3em;
 display: table;
}

.admonition-title {
    font-size: 1.3em;
    font-weight: bold;
}

aside{
 float: right;
 width: 20%;
 display: table;
 padding: 1em;
 margin: 1em;
 margin-right: 0;
}

.footnote, .cite{
 width: 98%;
 display: table;
 border: 1px solid #ddd;
 padding: 0.5%;
 margin: 0.5%;
}

.footnote .du-label, .cite .du-label{
 float: left;
 height: 100%;
 width: 5%;
 margin-right: 1em;
 padding: 0.5%;
 text-align: center;
 display: table;
}

th, th p{
 font-weight: bold;
}

.field-label{
 font-weight: bold;
}

ol.arabic{
 list-style-type: decimal;
}

ol.loweralpha{
 list-style-type: lower-alpha;
}

ol.upperalpha{
 list-style-type: upper-alpha;
}

ol.lowerroman{
 list-style-type: lower-roman;
}

ol.upperroman{
 list-style-type: upper-roman;
}

img.align-left{
 float: left;
}

img.align-right{
 float: right;
}
</style></head><body><img alt="/static/images/54578303_p0.jpg" src="/static/images/54578303_p0.jpg"></body></html>

mainconv/templates/upload.html
<html>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
<head>
<title>rst2html - Upload image</title>
<script>
function get_name(){
	document.getElementById('name').value = document.getElementById('file').value;
}
</script>
</head>
<body>
<div class="main">
<form action="{% url 'mainconv:upload_img' %}" method="post" enctype="multipart/form-data">
{% csrf_token %}
	Image file : <input id="file" type="file" name="uploadedFile" accept="image/*" onchange="get_name()" required></br>
	Image name : <input id="name" type="text" name="name" required>
	<input type="submit" value="Submit">
</form>
</div>
</body>
</html>